
DROP TABLE IF EXISTS dbo.TB_CNPJ
GO
CREATE TABLE dbo.TB_CNPJ(
CNPJ  VARCHAR(2000),
RAZAO_SOCIAL  VARCHAR(2000),
NATUREZA_JURIDICA  VARCHAR(2000),
QUALIFICACAO_RESPONSAVEL  VARCHAR(2000),
CAPITAL_SOCIAL VARCHAR(2000),
PORTE_EMPRESA  VARCHAR(2000),
ENTE_FEDERATIVO VARCHAR(2000),
NM_ARQUIVO VARCHAR(2000),
DH_INCLUSAO DATETIME NOT NULL DEFAULT GETDATE()
)
GO

SELECT COUNT(1) TOTAL_REG
, MIN([DH_INCLUSAO]) DH_INICIO 
, MAX([DH_INCLUSAO]) DH_FIM
, DATEDIFF(MINUTE, MAX([DH_INCLUSAO]), MIN([DH_INCLUSAO])) TEMPO_GASTO
FROM dbo.TB_CNPJ
GO